name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Native Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libexif-dev pkg-config
    - uses: actions/checkout@v4
    - name: Download Build Cache
      uses: actions/cache@v4.2.3
      with:
        path: target/
        key: ci-rs-build-cache
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
